import React from 'react'

function Card({  title, num, num1, num2, num3 }) {
  return (
  
    <>
    <div className='flex p-5 rounded-2xl flex-col justify-center items-center gap-6 border text-center  '>
  
    <div>    <h1 className=' font-medium text-2xl'>Waves + {title} Module</h1>
    <h1 className='font-medium text-sm  text-start' >{num} features</h1>
</div >
<div >
  <h1 className='font-medium text-sm  text-start '>Start at</h1>
     <h1 className='font-normal text-xl text-start ' > ${num1}/month</h1>
</div>
<div>
  <h1 className='font-medium text-sm  text-start'>+{num3} off revenue generated by websb</h1>
  <h1 className='font-medium text-sm  text-start'>16.66%-discount</h1>
</div >
<div className='w-full'><button className='text-center  bg-[#fee208] p-2 w-full rounded-xl '>
  Buy now
  </button></div>
  <div className='font-normal bg-gray-300 border p-1.5 border-r-zinc-800 rounded-xl w-36 text-sm  text-center'>
    <h1>Up to {num2}</h1>

  </div>
    
    </div>
    </>
  )
}

export default Card