import React from 'react'
import api from '../utills/api.js';
function Card({  title, num, price, num2, num3 }) {
 
   const handlePayment = async () => {
    try {
      const { data } = await api.post("payment/create-order", {
        amount:price , // example: ₹499
      });

      const options = {
        key: import.meta.env.VITE_RAZORPAY_KEY_ID, // from .env
        amount: data.order.amount,
        currency: "INR",
        name: "WebSB",
        description: "Buy Now Plan",
        order_id: data.order.id,
        handler: async function (response) {
          // Verify payment
          const verify = await api.post("payment/verify", response);
          if (verify.data.success) alert("Payment Successful 🎉");
          else alert("Payment verification failed ❌");
        },
        prefill: {
          name: "John Doe",
          email: "john@example.com",
          contact: "9999999999",
        },
        theme: {
          color: "#121212",
        },
      };

      const rzp = new window.Razorpay(options);
      rzp.open();
    } catch (error) {
      console.error(error);
      alert("Something went wrong");
    }
  };
  return (
  
    <>
    <div className='flex p-5 rounded-2xl flex-col justify-center items-center gap-6 border text-center  '>
  
    <div>    <h1 className=' font-medium text-2xl'>Waves + {title} Module</h1>
    <h1 className='font-medium text-sm  text-start' >{num} features</h1>
</div >
<div >
  <h1 className='font-medium text-sm  text-start '>Start at</h1>
     <h1 className='font-normal text-xl text-start ' >₹{price}/month</h1>
</div>
<div>
  <h1 className='font-medium text-sm  text-start'>+{num3} off revenue generated by websb</h1>
  <h1 className='font-medium text-sm  text-start'>16.66%-discount</h1>
</div >
<div onClick={handlePayment} className='w-full'><button className='text-center  bg-[#fee208] p-2 w-full rounded-xl '>
  Buy now
  </button></div>
  <div className='font-normal bg-gray-300 border p-1.5 border-r-zinc-800 rounded-xl w-36 text-sm  text-center'>
    <h1>Up to {num2}</h1>

  </div>
    
    </div>
    </>
  )
}

export default Card